version: 2

models:
  - name: orders
    description: Information regarding orders
    columns:
      - name: order_id
        description: The order ID, unique identifier for an order

      - name: order_loaded_at
        description: Timestamp to indicate when the record was loaded into the table

      - name: order_created_at
        description: Timestamp to indicate when the order was created

      - name: order_updated_at
        description: Timestamp to indicate when the order was last updated

      - name: order_subtotal
        description: The dollar sum of all line item amounts after discounts but before shipping, taxes, and tips (in USD)

      - name: order_total
        description: The dollar sum of all line item amounts, discounts, shipping, taxes, and tips (in USD)
      
      - name: line_items
        description: Array of all existing line items associated with each order
  
  - name: products
    description: Information regarding products
    columns:
      - name: product_id
        description: The product ID, unique identifier for a product

      - name: product_loaded_at
        description: Timestamp to indicate when the record was loaded into the table

      - name: product_created_at
        description: Timestamp to indicate when the product was created in the e-commerce system

      - name: product_updated_at
        description: Timestamp to indicate when the product was last updated in our e-commerce system

      - name: product_title
        description: The title of the product

      - name: variants
        description: >
          Array of all existing product variants associated with the product, each variant representing a different version of the product
  
  - name: web_events  
    description: Information regarding web events
    columns:
      - name: web_event_id
        description: The web event ID, unique identifier for the event

      - name: _loaded_at
        description: Timestamp to indicate when the record was loaded into the table

      - name: cookie_id
        description: >
          Device identifier used to indicate a website visitor.
          For a new visitor, this value is set in the user's browser cookies.

      - name: customer_id
        description: Unique identifier to indicate a customer. This value is null if the user is an anonymous web visitor

      - name: event_name
        description: Event name that indicates how user interacted with the website

      - name: event_url
        description: URL on which the event occurred

      - name: event_properties
        description: JSON string containing contextual properties relating to the event

      - name: timestamp
        description: Timestamp to indicate when the event occurred

      - name: utm_campaign
        description: Campaign that referred the user

      - name: utm_medium
        description: Medium that referred the user

      - name: utm_source
        description: Source that referred the user

