version: 2

sources: 
  - name: boll
    description: Source data
    schema: ae_data_challenge_v1
    tables: 
      - name: orders
        identifier: orders
      
      - name: products
        identifier: products
        
      - name: web_events
        identifier: web_events